// 'use server'
import "./css/style.css";
import "./[local]/ui/global.css";
import { Inter, Architects_Daughter } from "next/font/google"; //Inter font 字体样式库
import {
  AbstractIntlMessages,
  NextIntlClientProvider,
  useMessages,
} from "next-intl";
import { getMessages } from "next-intl/server";
import Header from "@/src/app/[local]/ui/home/header";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const architects_daughter = Architects_Daughter({
  subsets: ["latin"],
  variable: "--font-architects-daughter",
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "Hanglok Remind",
  description: "Generated by create next app",
};
export default  function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body
        className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased text-black tracking-tight`}
      >
        <NextIntlClientProvider
          locale={locale}
          messages={messages as AbstractIntlMessages}
        >
          <div className="flex flex-col min-h-screen overflow-hidden">
            <Header />
            {children}
            {/* <Banner /> */}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
